# Uncomment the next line to define a global platform for your project
platform :ios, '15.5'

target 'Darkslide' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Darkslide
	pod 'SwiftGen', '~> 6.0'
	pod 'Factory'
 	pod 'SwiftyMocky'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'GoogleSignIn'
end
